name: speech-acts
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bidict=0.21.2
  - nltk=3.7
  - openpyxl=3.0.9
  - pip
  - python=3.7
  - python-crfsuite=0.9.8
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - pip:
    - pylangacq==0.17.0