name: speech-acts
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bidict=0.21.2
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - click=8.0.4
  - cycler=0.11.0
  - dbus=1.13.18
  - et_xmlfile=1.1.0
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nltk=3.7
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openpyxl=3.0.9
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.3.5
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.7.13
  - python-crfsuite=0.9.8
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.1
  - qt=5.9.7
  - readline=8.1.2
  - regex=2022.3.15
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=61.2.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.38.3
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.64.0
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - charset-normalizer==2.0.12
    - idna==3.3
    - pylangacq==0.17.0
    - requests==2.28.0
    - tabulate==0.8.9
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - wcwidth==0.2.5
